FROM python:3.9-slim

RUN apt-get update && \
  apt-get install -y sshpass && \
  rm -rf /var/lib/apt/lists/*

RUN pip install ansible

WORKDIR /ansible

COPY ./ansible /ansible

CMD ["ansible-playbook", "/ansible/playbook.yml"]
